### ISSUE TITLE
Problems with Indenting PHP when not inside <?php -- ?>

### ISSUE THREAD

**Issue by webplantmedia** [2072/PHP-Indenting-for-VIm#19]
Indents inside php files is not acting as the way described in the readme file.

![screen shot 2013-09-12 at 12 31 39 pm](https://f.cloud.github.com/assets/2718748/1132807/7c3ff112-1bd1-11e3-8db4-79df8215b6ee.jpg)

However, I know the plugin is working because writing code inside of functions works perfectly. Even writing switch statements. I can also read the help text provided from within vim.

![screen shot 2013-09-12 at 12 36 40 pm](https://f.cloud.github.com/assets/2718748/1132831/f262425a-1bd1-11e3-86ff-572f4c659c16.jpg)

I downloaded 7.4.22 MacVim and Vim from homebrew on my Mac.

Notable settings in my .vimrc include:
filetype plugin indent on
set nocompatible
set noexpandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set lbr
set tw=500
set showbreak=----->
set nosmartindent
set autoindent
set nocindent
set wrap "Wrap lines
let g:PHP_vintage_case_default_indent = 1
let g:PHP_removeCRwhenUnix = 1

Here is a snapshot of plugins I'm using along with pathogen.

![screen shot 2013-09-12 at 12 41 36 pm](https://f.cloud.github.com/assets/2718748/1132867/abc54b2a-1bd2-11e3-846f-c757a92db502.jpg)

Is there any settings that I need set or disabled? Or are there any plugins that can conflict with php-indent? Thanks!

**Comment by GeneralFailer** [comment]
Why is the alternative syntax not supported though?

**Comment by 2072** [comment]
Because I created this indentation script more than 13 years ago and you are the first person to ask this question.
