### ISSUE TITLE
Indent empty lines

### ISSUE THREAD

**Issue by jrean** [2072/PHP-Indenting-for-VIm#43]
Hi,

How to manage empty lines?

```
if(true) {
    $var = "foo";
// empty line
    $foo = "var";
}
```

I would like Vim to keep indentation on empty lines.
Can you help?

Thank you for your work.

**Comment by 2072** [comment]
You mean that you want to have spaces/tabs on empty lines? For what reasons would need such a feature?

**Comment by 2072** [comment]
I'm closing this because no reply... I cannot implement such a feature without a good reason/use scenario.
