### ISSUE TITLE
Multiline class properties break indentation

### ISSUE THREAD

**Issue by Ilyes512** [2072/PHP-Indenting-for-VIm#47]
So, today I found out that a multiline class property breaks the indentation for the file. I will try and describe it by giving example's:

I start of with the below, where `//[]` equals my current cursor position with `insert`-mode:

```php
<?php

class testing
{
    protected $testing = 'This is a multiline
        property value
        that continues over multiple
        lines';//[]
}
```

When I hit return the cursor goes to the next line, but the indent is wrong:

```php
<?php

class testing
{
	protected $testing = 'This is a multiline
		property value
		that continues over multiple
		lines';
//[]
}
```

Note the cursor position. So if I start inserting the next property without hitting tab again I get this:

```php
<?php

class testing
{
    protected $testing = 'This is a multiline
        property value
        that continues over multiple
        lines';

protected $foobar;

}
```

Even when I manually override the spacing and insert the tabs after the fact like this:

```php
<?php

class testing
{
    protected $testing = 'This is a multiline
        property value
        that continues over multiple
        lines';

    protected $foobar;

    public function __construct() {
        echo 'hello world';
    }
}
```

Once I hit `gg=G` to reformat the current file's spacing. It changes it to:

```php
<?php

class testing
{
    protected $testing = 'This is a multiline
        property value
        that continues over multiple
        lines';

protected $foobar;

public function __construct() {
    echo 'hello world';
}
}
```

I am not really sure if it's my configuration or the plugin it self. My dotfiles can be found in my repository on github right [here](https://github.com/Ilyes512/mydotfiles). More specifically my .vimrc can be found [here](https://github.com/Ilyes512/mydotfiles/blob/master/vimrc.vim) and my plugin file [here](https://github.com/Ilyes512/mydotfiles/blob/master/vim/plugins.vim).

I can also tell you that vim does recognize the file as php (`:set filetype?` returns `filetype=php`). If you need some more info just ask. I can usually answer very quickly (if I can).

**Comment by h3xx** [comment]
Something I noticed was that the semicolon placement matters:

    class testing {
        protected $testing = 'This is a multiline
            property'
    ;
        protected $foobar;
    }

The `$foobar` property indents correctly.

**Comment by 2072** [comment]
I'll check this out but you should use [heredoc/nowdoc](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) notation which is properly supported and reliable. Multi-line strings are very difficult to identify correctly (without a real parser) and insert an uncontrollable number of spaces in your strings...

**Comment by Ilyes512** [comment]
@2072 I understand there is heredoc/nowdoc, but ideally I would still like to use multiline properties anyways.

I understand that this might be hard or even not feasible. I still would like to thank you for you time in any case :)

(BTW I don't know how this plugin works, still a noob with Vim. I will try and understand how it's implemented to get a feeling.)

**Comment by andrey-utkin** [comment]
Experiencing similar difficulty. In a codebase of project I'm participating, we have SQL queries formatted as quoted.

```
<?php

class A
{
    public function a()
    {
        $query =
            "UPDATE mytable
                SET a = 'a'
          RETURNING *";

        $a = f("a", "b",
               "c");
    }
}
```

And when you go to edit `$a = f("a", "b",` to move "b" to next line, you get:

```
<?php

class A
{
    public function a()
    {
        $query =
            "UPDATE mytable
                SET a = 'a'
          RETURNING *";

$a = f("a",
    "b",
               "c");
    }
}
```

What is most annoying is that alignment of the beginning of the line, `$a = f("a",`, gets messed up.

Is there any flag i could tweak?

**Comment by 2072** [comment]
I have no time to look into this right now or any time soon (not before the end of July).

Besides using here/nowdoc _(which also adds the benefit of enabling syntax highlighting if you use the SQL keyword)_ one could also write this kind of code in the following way:

```php
class A
{
    public function a()
    {
        $query =
            "UPDATE mytable"
            ." SET a = 'a'"
            ." RETURNING *";

        $a = f("a", "b",
            "c");
    }
}
```

This is quite cleaner and avoids passing random spaces/tabs/line breaks to your query parser...

And with nowdoc style:

```php
class A
{
    public function a()
    {
        $query = <<<'SQL'
            UPDATE mytable
                SET a = 'a'
          RETURNING *
SQL;

        $a = f("a",
            "b",
            "c");
    }
}
```

**Comment by 2072** [comment]
OK this is fixed for now but as expected it was quite annoying to do. It may break again depending on what text you write in your multi-line strings... I've added a fail-safe to prevent breaking indentation if the start of the multi-line string declaration cannot be found.

As stated in https://github.com/2072/PHP-Indenting-for-VIm/issues/22#issuecomment-33920352, the safest way to write these is:

```php
class testing
{
    protected $testing = '
        This is an ugly multiline
        property value
        that continues over multiple
        lines';
}
```

so that, just like with herdoc, there is a way to look for the start of the declaration while safely skipping the string's content...
