### ISSUE TITLE
Broken in some nested sentence

### ISSUE THREAD

**Issue by 0xBADDCAFE** [2072/PHP-Indenting-for-VIm#49]
Like below sentence.

``` php
<?php

if (count([
  1,  // needs more one level
  2,
  3,
  4,
])) {
expr;   // not indented
}
```

Expected:

``` php
<?php

if (count([
    1,
    2,
    3,
    4,
])) {
  expr;
}
```

**Comment by 0xBADDCAFE** [comment]
Thanks 👍

**Comment by h-east** [comment]
@2072 Hi,
Is it possible to send latest version to vim_dev?
Pull-Request is fine.
BTW, the version of vim/runtime/indent/php.vim is [1.60](https://github.com/vim/vim/blob/master/runtime/indent/php.vim#L7).

**Comment by 2072** [comment]
done :)

**Comment by h-east** [comment]
@2072 Thank you:+1:
