### ISSUE TITLE
syntax highlight error

### ISSUE THREAD

**Issue by xuecai** [2072/PHP-Indenting-for-VIm#50]
when string  variable contains "?>", syntax highlight will be wrong since after zhe string;

example:
<?php
$str = "?>";$a="b";

 $a="b"; show me a wrong syntax highlight

**Comment by 2072** [comment]
This project is about the indentation script not the syntax parser.

You can try [my version of the syntax script](https://github.com/2072/vim-syntax-for-PHP), but since it's optimized for pure PHP files it may not work better.
