### ISSUE TITLE
Indentation of the curly braces not working after setting hi PhpParent

### ISSUE THREAD

**Issue by marekkon** [2072/PHP-Indenting-for-VIm#52]
I get:

``` php
public function zero()
{
    }
```

**Comment by 2072** [comment]
what syntax script are you using and how do you set this option?

**Comment by marekkon** [comment]
I forgot to mention that I use neovim.
I use the default syntax, but also tried it with `'StanAngeloff/php.vim'`.
Highlight is set in local colorscheme (`nvim/colors`). Directly setting this in `init.vim` gives the same effect.

**Comment by 2072** [comment]
Can you provide complete phpParent highlight example please?

**Comment by marekkon** [comment]
Currently it is
```vim
hi link    PhpParent      Normal
```
but earlier it was (same effect)
```vim
hi link    PhpParent      guifg=#999b9e
```

After some additional tests it turned out that any use of the PhpParent causes malfunction. E.g. if I comment out PhpParent highlight but leave something like this:
```vim
hi link    jsonBraces      PhpParent
```
then indentation doesn't work either.

**Comment by 2072** [comment]
I'm sorry but I'm still unable to reproduce this issue. I was using GVim8.0.69, I've just compiled the latest 8.0.514 and I still can't reproduce the issue.

You're probably experiencing a bug from your version of vim.

The indent script relies on the syntax name attribute to decide if the element needs indentation or not.

Put your cursor on a brace and run the following command:
```viml
:echo synIDattr(synID(line("."), col("."), 0), "name")
```

it should write `phpParent`. The indent script ignores almost everything that doesn't start with 'php'.

**Comment by marekkon** [comment]
`PhpParent` it is.

**Comment by jamessan** [comment]
Vim doesn't care about the case of the highlight groups.  It considers `phpParent` the same as `PhpParent`.  This means that if the user defines `PhpParent` before the syntax script defines `phpParent`, the synID information will report `PhpParent`.

The indent script probably should remove case-sensitive requirement for the matches.

```vim
    if synname == "Delimiter" || synname == "phpRegionDelimiter" || synname =~# "^phpParent" || synname == "phpArrayParens" || synname =~# '^php\%(Block\|Brace\)' || synname == "javaScriptBraces" || synname =~# '^php\%(Doc\)\?Comment' && b:UserIsTypingComment
```

**Comment by marekkon** [comment]
Wow, so simple fix after all this time.
Thanks.

**Comment by 2072** [comment]
@marekkon: I never noticed the uppercase P of `PhpParent` in your comments...

**Comment by marekkon** [comment]
I would never think that it matters, especially since the rest of the highlight groups start with uppercase letters and they don't cause problems.
