### ISSUE TITLE
Indenting problem

### ISSUE THREAD

**Issue by axbender** [2072/PHP-Indenting-for-VIm#57]
A "{" added after "foreach ..." in the following file will not get indented correctly (no variables regarding to PHP indenting were modified):

---------------------

```
<?php
   foreach ($defaults as $d_key => $d_val)
      {  << brace should be left-aligned with the beginning of "foreach"

   foreach ...
      {
xxx  << the next line feed takes me to here...
```

---------------------

I'm using version 1.62 of indent\php.vim with latest gvim.

**Comment by 2072** [comment]
I cannot reproduce this issue, can you check the value of the variable let PHP_BracesAtCodeLevel?

```viml
:let PHP_BracesAtCodeLevel
```

**Comment by axbender** [comment]
Thanks for reporting back: the value is 0, setting it to 1 has no apparent effect here.

**Comment by 2072** [comment]
can you check with 1.63 and make sure the script is indeed being loaded?

```VimL
:echo GetPhpIndentVersion()
```
this should print 1.63

**Comment by 2072** [comment]
This script doesn't rely on any html script but it relies on the syntax identifiers created by the the PHP Syntax script (several are compatible).
