### ISSUE TITLE
Array indentation gets broken

### ISSUE THREAD

**Issue by chitoku-k** [2072/PHP-Indenting-for-VIm#58]
I encountered a buggy behavior in array indentation that can be reproducible in following steps:

1. Run Vim without .vimrc: `vim -u NORC`
1. `let g:PHP_vintage_case_default_indent = 1`
1. `set ft=php`
1. Input some code which contains array(s):

```php
<?php
$x = [
];
$y = array(
);
```

after hitting return, the indentation becomes like this:

```php
<?php
$x = [
    ];
$y = array(
    );
```

This does not happen when `g:PHP_vintage_case_default_indent` is disabled (default).

Environment: Vim version 8.0.946

Thank you.

**Comment by 2072** [comment]
This should be fixed now.

**Comment by chitoku-k** [comment]
Yes it is! Thanks.
