### ISSUE TITLE
Multiline strings break indentation

### ISSUE THREAD

**Issue by LaserMoai** [2072/PHP-Indenting-for-VIm#60]
The last line there doesn't get indented properly.

```
<?php
if ($v) {
        echo "
";
echo "";
```

Version 1.62

**Comment by 2072** [comment]
I'm unable to reproduce this issue.

Could you install the new 1.63 version and try again?

With 1.63 version you can type the following command to check if the indent script was indeed loaded:
```VimL
:echo GetPhpIndentVersion()
```
this should print 1.63

**Comment by 2072** [comment]
I was able to reproduce a similar problem but you should check issue #47 as this is related. I'll fix it when I'll have some time but you really should be using heredoc notation instead of multi-line strings...

**Comment by GeneralFailer** [comment]
I'm just following examples from "PHP and MySQL for Dynamic Web Sites: Visual QuickPro Guide."

**Comment by h3xx** [comment]
Can confirm.

Given the following file:

    <?php

    class Foo
        public function bar() {
            $foo = "
    ";
        }
    }

Pressing Enter in insert mode after the ; on the `";` line puts the insertion point one st to the left of where it should be.

Oddly enough:

* entering a new one-line statement on the line after the `";` then pressing `==` indents the line correctly.
* pressing `cc` on an empty line after the `";` results in the insertion point being set correctly.

A relates issue:

Given the following file:

    <?php

    class Foo
        public function bar() {
            $foo = "
    ";
    $baz = "bar";
        }
    }

* Pressing `=ap` in command mode when the cursor is on any point in the class **NOT** indent the `$baz` line correctly.
* But pressing `==` on the `$baz` line indents it correctly.

Expected indenting in this case would be to align the `$` of the `$baz` line to the `$` in the `$foo` line.
