### ISSUE TITLE
Function-returning-reference body indenting

### ISSUE THREAD

**Issue by h3xx** [2072/PHP-Indenting-for-VIm#62]
Given the following file:

    <?php
    class Foo {
        public function &bar() {
            $foo = 0;
        }
    }

Indenting the class (`gg=G`) causes the function body and end-of-function brace to be indented one sw to the left of where it should be:

    <?php
    class Foo {
        public function &bar() {
        $foo = 0;
    }
    }

**Comment by 2072** [comment]
Thanks for the report that was easy to fix!

**Comment by h3xx** [comment]
Confirmed fixed. Thanks!
