### ISSUE TITLE
Incorrect indentation for multi-line function declarations with annotated returns

### ISSUE THREAD

**Issue by quexxon** [2072/PHP-Indenting-for-VIm#64]
Multi-line function declarations with an annotated return and the opening brace on the same line as the closing parentheses have incorrectly indented bodies. Note that the behavior is correct if the type annotation for the return is omitted.

# Example

## Current Behavior

```php
function add(
    int $x,
    int $y
): int {
return $x + $y;
}
```

## Expected Behavior

```php
function add(
    int $x,
    int $y
): int {
    return $x + $y;
}

```

**Comment by 2072** [comment]
This should be fixed now. Thanks for reporting this!
