### ISSUE TITLE
Misalign with switch

### ISSUE THREAD

**Issue by Mte90** [2072/PHP-Indenting-for-VIm#66]
With a code like this one:
```
    switch($country){
    case 'AT': // blabla
        $isValid = (bool) true;
        break;
    case 'BE': // blabla
        $isValid = (bool) true;
        break;
[...]
```
I get this alignment, if I fix manually a save will change the code as my example.

**Comment by 2072** [comment]
If the problem is the `switch` and `case` being indented at the same level, this is expected behavior, see: https://github.com/2072/PHP-Indenting-for-VIm/issues/56.

**Comment by Mte90** [comment]
Confirmed this fix the issue. I forgot to check the doc folder in VIM -.-' I checked only the readme.
