### ISSUE TITLE
GetPHPIndent freeze

### ISSUE THREAD

**Issue by einars** [2072/PHP-Indenting-for-VIm#75]
Attempting to add a line after this construction seems to throw the indentation algorithm into an infinite loop,
```
<?php

("
", ('', x));

```

To reproduce, create a file with the specified contents, open with *vim, put cursor on the last line and press 'o'. Observe freeze.

**Comment by einars** [comment]
Bisect shows that the freeze was introduced by commit c80bfb95:

Fix #60 where multiline-string declarations endings with nothing else before would break indentation.

**Comment by 2072** [comment]
Thanks for the report.
