### ISSUE TITLE
strange behaviour when last } is inlined

### ISSUE THREAD

**Issue by gcb** [2072/PHP-Indenting-for-VIm#87]
inherited some code with style:

```php
require_once('Debug.php');
$baseDebug = new Debug();
function debug( mixed $txt, bool $error=false, bool $force=false ): void{
	global $baseDebug;
	$baseDebug->debug( $txt, $error, $force ); }
function error(string $txt): void{
	global $baseDebug;
	$baseDebug->error( $txt ); }
function debug_flush_to_screen_debug_during_headers(){
	global $baseDebug;
	return $baseDebug->debug_flush_to_screen_debug_during_headers(); }
```

vim is running with
```vim
filetype=php
filetype detection:ON  plugin:ON  indent:ON
```

I have the tested both the `syntax/php.vim` from this repo and from the repo linked on the README with latest fixes.

after indenting this block i get:
```php
require_once('Debug.php');
$baseDebug = new Debug();
function debug( mixed $txt, bool $error=false, bool $force=false ): void{
	global $baseDebug;
	$baseDebug->debug( $txt, $error, $force ); }
	function error(string $txt): void{
		global $baseDebug;
		$baseDebug->error( $txt ); }
		function debug_flush_to_screen_debug_during_headers(){
			global $baseDebug;
			return $baseDebug->debug_flush_to_screen_debug_during_headers(); }
```

**Comment by gcb** [comment]
thank *you*! i was trying to fix these last days, but failing. I don't think i will go anywhere.

**Comment by 2072** [comment]
OK this is fixed.

This script uses a lot of heuristics to do its job, when debugging you need to do 2 things:
- comment out the `finish` in:

```viml
" Only define the functions once per Vim session.
if exists("*GetPhpIndent")
    call ResetPhpOptions()
    finish " XXX -- comment this line for easy dev
endif
```

and enable the debug by executing the command: `:%s /" DEBUG \zec//g`  (you can disable them with `:%s /^\s*\zs\zecall DebugPrintReturn/" DEBUG /g`)

Then try to indent the line causing issues and follow what is happening to find out which part of the script is causing the issue.

I'm going to add this to the readme.md.
